,categories: [ "Beruf & Arbeit",
      "Gesellschaft & Politik",
      "Technik & Fortschritt",
      "Wirtschaft & Konsum",
      "Feiertage & Religion",
      "Umwelt & Klima",
      "Gesundheit & Körper",
      "Zwischenmenschliches",
      "Bildung & Intelligenz",
      "Service & Dienstleistung",
      "Höllisch gut",
      "Chef*innen & Clowns",
      "Systemkritisch charmant",
      "Sinnkrisen & Donuts",
      "Für Fortgeschrittene",
      "Randale & Romantik",
      "Unbequeme Wahrheiten",
      "Echte Klassiker",
      "Zukunftsängste",
      "Sport & Fitness",
      "Essen & Trinken"] 